name: checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run lint checks
        run: npm run lint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npx prettier --check '**/*.md'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          export SEED=$(openssl rand -hex 16)
          echo $SEED
          npm run test
